version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - VITE_JWT_KEY=${VITE_JWT_KEY}
      - VITE_MOGODB_URI=mongodb://mongo:27017/movies
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80'
    depends_on:
      - backend
    environment:
      - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
      - NODE_ENV=production

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
